services:
  - type: web
    name: phishing-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app.py --server.port 10000 --server.enableCORS false"
